url: https://graupellabs.com
baseurl: "/"
title: Graupel Labs
author:
  name: Graupel Labs, Inc.
  email: contact@graupellabs.com
description: >
  Aerospace image processing and data analysis done right.

minima:
  skin: auto

  social_links:
    - { platform: github,   user_url: "https://github.com/GraupelLabs" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/GraupelLabs" }

remote_theme: jekyll/minima@1e6da7d

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
